name: EasyDB
main: com.simplyian.easydb.EasyDBPlugin
version: 0.1.0
author: AlbireoX
website: http://simplyian.com

commands:
  dbreload:
    desciption: Reloads the database.
    usage: /dbreload

permissions:
  easydb.reload:
    description: Allows reloading of the database.
