name: EasyDB
main: com.simplyian.easydb.EasyDBPlugin
version: 0.1.0
author: AlbireoX
website: http://simplyian.com

load: STARTUP

commands:
  dbconfig:
    description: Configures database credentials.
    usage: 'Usage: /dbconfig <host|port|user|pass|name> [value]'
  dbreload:
    desciption: Reloads the database.
    usage: 'Usage: /dbreload'

permissions:
  easydb.*:
    description: Gives all EasyDB permissions.
    children:
      - easydb.credentials
      - easydb.reload
  easydb.credentials:
    description: Allows manipulation and viewing of database credentials.
  easydb.reload:
    description: Allows reloading of the database.
